FROM orangeopensource/concourse:base

RUN bash -c "$(curl -fsSL https://raw.github.com/ArthurHlt/gitlab-accept-mr-cli/master/bin/install.sh)"
RUN bash -c "$(curl -fsSL https://raw.github.com/orange-cloudfoundry/cf-audit-actions/master/bin/install.sh)"
