name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  DOCKERHUB_ORG: orangecloudfoundry 
  IMAGES: buildpack
jobs:

  build:
    name: build, test and publish
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    -
      name: Login to GitHub Container Registry
      uses: docker/login-action@v1 
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    -
      name: build and publish 'buildpack' image
      uses: docker/build-push-action@v2
      with:
        context: ${{env.IMAGE}}
        push: true
        tags: |          
          ghcr.io/${{github.repository}}-${{env.IMAGE}}:${{github.sha}}
          ghcr.io/${{github.repository}}-${{env.IMAGE}}:latest
        #${{env.DOCKERHUB_ORG}}/${{env.IMAGE}}:${{github.sha}}
      env:
        IMAGE: buildpack          
    
